---
title: "Survey data"
author: "M. E. Waggoner"
date: "June 22, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(readxl)


```

## The survey

```{r}
# Read in the raw data not using the row names
# because they contain non-ascii characters
# Assign NA to all relevant strings
read_excel("AnneData.xlsx", 
            col_names = FALSE,
            na = c("N/A", "n/a", "NA", "na", "Na", "N/a", "Not applicable", "",
                   "Not applicable; my family member does not attend a Down syndrome specialty clinic") ) -> 
  DSSurveyraw
```

```{r}
#######################################
#
# Initial cleaning of variables that can
# be done in bulk
#



######################################
# Rename the variables and store in a new tibble

DSSurveyraw %>% 
  rename( ID1	=	X__1	,
          ID2	=	X__2	,
          ID3	=	X__3	,
          ID4	=	X__4	,
          ID5	=	X__5	,
          ID6	=	X__6	,
          ID7	=	X__7	,
          ID8	=	X__8	,
          ID9	=	X__9	,
          DSbirthyear	=	X__10	,
          DStype	=	X__11	,
          relationship	=	X__12	,
          independent	=	X__13	,
          guardian	=	X__14	,
          firstnotified	=	X__15	,
          firstnotified2	=	X__16	,
          autism	=	X__17	,
          ADHD	=	X__18	,
          therapy_PT	=	X__19	,
          therapy_OT	=	X__20	,
          therapy_feeding	=	X__21	,
          therapy_speech	=	X__22	,
          therapy_music	=	X__23	,
          therapy_equine	=	X__24	,
          DSeducation	=	X__25	,
          DSvisit	=	X__26	,
          clinic	=	X__27	,
          clinic_noneed	=	X__28	,
          clinic_full	=	X__29	,
          clinic_inaccessible	=	X__30	,
          clinic_notime	=	X__31	,
          clinic_noinsur	=	X__32	,
          clinic_none	=	X__33	,
          clinic_na	=	X__34	,
          clinicdistance	=	X__35	,
          visitstotal	=	X__36	,
          visitsplanned	=	X__37	,
          visitsunplanned	=	X__38	,
          visitsemergency	=	X__39	,
          transporttype	=	X__40	,
          transporttype2	=	X__41	,
          traveltime	=	X__42	,
          insurance	=	X__43	,
          insurance2	=	X__44	,
          treatments	=	X__45	,
          treatments2	=	X__46	,
          health_celiac	=	X__47	,
          health_diabetes	=	X__48	,
          health_leuk	=	X__49	,
          health_apnea	=	X__50	,
          health_lowiron	=	X__51	,
          health_thyroid	=	X__52	,
          health_swallaw	=	X__53	,
          health_ALZ	=	X__54	,
          health_hiBP	=	X__55	,
          health_CDH	=	X__56	,
          health_none	=	X__57	,
          health2	=	X__58	,
          diag_celiac	=	X__59	,
          diag_diabetes	=	X__60	,
          diag_leuk	=	X__61	,
          diag_apnea	=	X__62	,
          diag_lowiron	=	X__63	,
          diag_thyroid	=	X__64	,
          diag_swallow	=	X__65	,
          diag_ALZ	=	X__66	,
          diag_hiBP	=	X__67	,
          diag_CDH	=	X__68	,
          diag_other	=	X__69	,
          concern_celiac	=	X__70	,
          concern_diabetes	=	X__71	,
          concern_leuk	=	X__72	,
          concern_apnea	=	X__73	,
          concern_lowiron	=	X__74	,
          concern_thyroid	=	X__75	,
          concern_swallow	=	X__76	,
          concern_ALZ	=	X__77	,
          concern_hiBP	=	X__78	,
          concern_CDH	=	X__79	,
          concern_other	=	X__80	,
          livingsituation	=	X__81	,
          livingsituation2	=	X__82	,
          substance_abuse	=	X__83	,
          substance_abuse2	=	X__84	,
          substance_none	=	X__85	,
          substance_12step	=	X__86	,
          substance_therapy	=	X__87	,
          substance_limit	=	X__88	,
          substance_other	=	X__89	,
          mentaldiag	=	X__90	,
          mentaldiag_OCD	=	X__91	,
          mentaldiag_dep	=	X__92	,
          mentaldiag_anxiety	=	X__93	,
          mentaldiag_bipolar	=	X__94	,
          mentaldiag_schiz	=	X__95	,
          mentaldiag_other	=	X__96	,
          mentaltreat	=	X__97	,
          mentaltreat_cognitive	=	X__98	,
          mentaltreat_group	=	X__99	,
          mentaltreat_drugs	=	X__100	,
          mentaltreat_ECT	=	X__101	,
          mentaltreat_TMS	=	X__102	,
          mentaltreat_noaccess	=	X__103	,
          mentaltreat_other	=	X__104	,
          mental_will_now	=	X__105	,
          mental_will_future	=	X__106	,
          mental_will_untestable	=	X__107	,
          mental_will_side	=	X__108	,
          mental_will_time	=	X__109	,
          mental_will_interact	=	X__110	,
          mental_will_faith	=	X__111	,
          mental_will_culture	=	X__112	,
          mental_will_nomed	=	X__113	,
          mental_will_na	=	X__114	,
          mental_will2	=	X__115	,
          regress	=	X__116	,
          regress_cat	=	X__117	,
          regress_dress	=	X__118	,
          regress_RW	=	X__119	,
          regress_social	=	X__120	,
          regress_attend	=	X__121	,
          regress_selfcare	=	X__122	,
          regress2	=	X__123	,
          sex	=	X__124	,
          sexED_no	=	X__125	,
          sexED_danger	=	X__126	,
          sexED_bound	=	X__127	,
          sexED_prevent	=	X__128	,
          sexED_health	=	X__129	,
          sexED_WS	=	X__130	,
          sexED_other	=	X__131	,
          future_access	=	X__132	,
          future_opps	=	X__133	,
          future_housing	=	X__134	,
          future_employ	=	X__135	,
          future_ALZ	=	X__136	,
          future_woGuardian	=	X__137	,
          healthcare_respond	=	X__138	,
          healthcare_DS	=	X__139	,
          healthcare_group	=	X__140	,
          healthcare_PCP	=	X__141	,
          healthcare_clinic	=	X__142	,
          state_reported	=	X__143	,
          gender_respond	=	X__144	,
          gender_DS	=	X__145	,
          race_respond	=	X__146	,
          race_respond2	=	X__147	,
          language	=	X__148	,
          language2	=	X__149	,
          income	=	X__150	,
          ed_respond	=	X__151	) -> DSSurvey

###############################################
# Remove rows and columns that are untidy or
# contain private information
#

# delete identifier columns and 
# delete rows 2 and 3, which do not contain data
DSSurvey %>% 
  select(-starts_with("ID")) %>% 
  slice(-1:-2) -> 
  DSSurvey

# Add an index column
# and put it first
DSSurvey$index <- 1:nrow(DSSurvey)
DSSurvey %>% 
  select(index, everything()) ->
  DSSurvey



###################################
# Set variable classes
#

# List columns to convert Yes/No responses to logical
logical_cols <- c("ADHD",
                  "autism",
                  "substance_abuse"
                  )  

# List columns to convert short list responses to factor
factor_cols <- c( "clinic",
                  "diag_ALZ",
                  "diag_apnea",
                  "diag_CDH",
                  "diag_celiac",
                  "diag_diabetes",
                  "diag_hiBP",
                  "diag_leuk",
                  "diag_lowiron",
                  "diag_other",
                  "diag_swallow",
                  "diag_thyroid",
                  "DStype",
                  "firstnotified",
                  "firstnotified2",
                  "gender_DS",
                  "gender_respond",
                  "guardian",
                  "health2",
                  "insurance",
                  "language",
                  "language2",
                  "livingsituation",
                  "livingsituation2",
                  "mental_will2",
                  "mentaldiag",
                  "mentaldiag_other",
                  "mentaltreat",
                  "mentaltreat_other",
                  "race_respond",
                  "race_respond2",
                  "regress",
                  "regress2",
                  "relationship",
                  "sex",
                  "sexED_other",
                  "substance_abuse2",
                  "transporttype",
                  "transporttype2",
                  "treatments",
                  "treatments2")

# List columns to convert responses to numeric
numeric_cols <- c("concern_ALZ",
                  "concern_apnea",
                  "concern_CDH",
                  "concern_celiac",
                  "concern_diabetes",
                  "concern_hiBP",
                  "concern_leuk",
                  "concern_lowiron",
                  "concern_other",
                  "concern_swallow",
                  "concern_thyroid",
                  "future_access",
                  "future_ALZ",
                  "future_employ",
                  "future_housing",
                  "future_opps",
                  "future_woGuardian",
                  "healthcare_clinic",
                  "healthcare_DS",
                  "healthcare_group",
                  "healthcare_PCP",
                  "healthcare_respond"
                  )

# List columns that should be logical
# and set to TRUE if there is content in the cell
# because they are "choose all that apply" responses
all_that_apply_cols <- c( "clinic_full",
                          "clinic_inaccessible",
                          "clinic_na",
                          "clinic_noinsur",
                          "clinic_none",
                          "clinic_noneed",
                          "clinic_notime",
                          "health_ALZ",
                          "health_apnea",
                          "health_CDH",
                          "health_celiac",
                          "health_diabetes",
                          "health_hiBP",
                          "health_leuk",
                          "health_lowiron",
                          "health_swallaw",
                          "health_thyroid",
                          "mental_will_culture",
                          "mental_will_faith",
                          "mental_will_interact",
                          "mental_will_na",
                          "mental_will_nomed",
                          "mental_will_side",
                          "mental_will_time",
                          "mental_will_untestable",
                          "mentaldiag_anxiety",
                          "mentaldiag_bipolar",
                          "mentaldiag_dep",
                          "mentaldiag_OCD",
                          "mentaldiag_schiz",
                          "mentaltreat_cognitive",
                          "mentaltreat_drugs",
                          "mentaltreat_ECT",
                          "mentaltreat_group",
                          "mentaltreat_noaccess",
                          "mentaltreat_other",
                          "mentaltreat_TMS",
                          "regress_attend",
                          "regress_cat",
                          "regress_dress",
                          "regress_RW",
                          "regress_selfcare",
                          "regress_social",
                          "sexED_bound",
                          "sexED_danger",
                          "sexED_health",
                          "sexED_no",
                          "sexED_prevent",
                          "sexED_WS",
                          "substance_12step",
                          "substance_limit",
                          "substance_other",
                          "substance_therapy"
                          )

# Columns where unsure = NA
unsure_cols <- c( "therapy_PT",
                  "therapy_OT",
                  "therapy_feeding",
                  "therapy_speech",
                  "therapy_music",
                  "therapy_equine"
                  )


# Make the conversions needed on the lists above
DSSurvey %>% 
  mutate_at(factor_cols, as.factor) %>% 
  mutate_at(logical_cols, funs(if_else( . == "Yes", TRUE, FALSE)) ) %>% 
  mutate_at(numeric_cols, as.numeric ) %>%
  mutate_at(all_that_apply_cols, funs(if_else( is.na(.), FALSE, TRUE)) ) %>% 
  mutate_at(unsure_cols, funs(if_else( . == "Yes", 
                                       TRUE, 
                                       if_else( . == "No", FALSE, NA))))->
  DSSurvey


##############################
# clean variables that need special  handling
#

# DSbirthyear has some non-numeric characters  - so remove them
# the format is not alway %Y, but sometimes %m/%d/%Y - so pull
#   off right-most 4 digits
# then convert to numeric
DSSurvey %>%
  mutate(DSbirthyear = gsub("[^0-9/]", "", DSbirthyear)) %>%
  mutate(DSbirthyear = str_sub(DSbirthyear,-4,-1)) %>%
  mutate(DSbirthyear = as.numeric(DSbirthyear)) ->
  DSSurvey

# create an age column based on DSbirthyear
DSSurvey %>% 
  mutate(DSage = 2018 - DSbirthyear) ->
  DSSurvey



# factor variables where levels need to be ordered
DSSurvey %>%
  mutate(DSeducation = 
           factor(DSeducation,
                  levels = c("Completed middle school", 
                             "Some high school", 
                             "Graduated high school with certificate of completion", 
                             "Graduated high school with a high school diploma", 
                             "Some job training", 
                             "Completed a job training program", 
                             "Some college", 
                             "Completed a college program"))) %>%
  mutate(ed_respond = 
           factor(ed_respond,
                  levels = c("Completed high school", "Completed some college", 
                             "Associate's degree", "Bachelor's degree", 
                             "Completed some post-graduate", "Master's degree", 
                             "Other advanced degree beyond a Master's degree",
                             "Ph.D., law, or medical degree"))) %>%
  mutate(DSvisit = 
           factor(DSvisit, 
                  levels = c("No", "Yes; once", 
                             "Yes; yearly or more"))) %>%
  mutate(clinicdistance = 
           factor(clinicdistance,
                  levels = c("0-20 miles", "20-40 miles", 
                             "40-60 miles", "60-80 miles", 
                             "80-100 miles")))  %>% 
  mutate(income = 
           factor(income,
                  levels = c("Less than $10,000", "$10,000-25,000", 
                             "$25,000-35,000", "$35,000-50,000", 
                             "$50,000-75,000", "$75,000-100,000", 
                             "$100,000-150,000", "$150,000 or more"))) %>% 
  mutate(visitstotal = 
           factor(visitstotal,
                  levels = c("0-2", "3-5", 
                             "6-8", "9-11", 
                             "12 and over"))) %>% 
  mutate(visitsplanned = 
           factor(visitsplanned, 
                  levels = c("0-2", "3-5", 
                             "6-8", "9-11", 
                             "12 and over"))) %>% 
  mutate(visitsunplanned = 
           factor(visitsunplanned, 
                  levels = c("0-2", "3-5", 
                             "6-8", "9-11", 
                             "12 and over"))) %>% 
  mutate(visitsemergency = 
           factor(visitsemergency, 
                  levels = c("0-2", "3-5", 
                             "6-8", "9-11", 
                             "12 and over"))) %>% 
  mutate(traveltime = 
           factor(traveltime, 
                  levels = c("0-1 hours", "1-2 hours", 
                             "2-3 hours", "3-4 hours", 
                             "Over 4 hours"))) %>%
  mutate(mental_will_now = 
           factor(mental_will_now, 
                  levels = c("Definitely not", "Not sure", 
                             "Probably", "Definitely"))) %>%
  mutate(mental_will_future = 
           factor(mental_will_future,
                  levels = c("Definitely not", "Probably not", 
                             "Not sure", "Probably", 
                             "Definitely"))) ->
  DSSurvey

# clean up the state column
# first, create a tibble with state names, abbrevs,
# and other locations (DC, ON, India) and nonstandard names

st_w_errors <- tibble(state = state.name,
                       location_abb = state.abb) %>% 
  add_row(state = "District of Columbia", location_abb = "DC") %>% 
  add_row(state = "India", location_abb = "India") %>% 
  add_row(state = "Toronto, On", location_abb = "ON") %>% 
  add_row(state = "Mass", location_abb = "MA") %>% 
  add_row(state = "Mass.", location_abb = "MA") %>% 
  add_row(state = "Nys", location_abb = "NY") %>% 
  add_row(state = "Mi, Just Moved Here From Co", location_abb = "MI")

st_wo_errors <- tibble(state = state.name,
                       location_abb = state.abb)
  
DSSurvey %>%
  mutate(state_reported = str_to_title(state_reported)) %>%
  left_join(st_w_errors, by  = c("state_reported" = "state")) %>%
  mutate(location_abb = if_else(is.na(location_abb),
                                str_to_upper(state_reported),
                                location_abb))  %>%
  left_join(st_wo_errors, by = c("location_abb")) -> DSSurvey
                  
DSSurvey %>% 
  select(insurance, insurance2) %>% 
  mutate(test = funs(if(is.na(insurance) & 
                    str_detect(insurance2, "Medicaid")){
                      .<-as.factor("Public")}
         )
  )
                    
?str_detect                     
DSSurvey %>% 
  select(insurance, insurance2) %>% 
  filter(is.na(insurance))

dim(DSSurvey)






DSSurvey %>% 
  select(firstnotified, firstnotified2) %>% 
  filter(!is.na(firstnotified2)) %>% 
  write_excel_csv('firstnotified.csv')

levels(DSSurvey$firstnotified)

```

```{r}

# some examples of dplyr and ggplot

DSSurvey %>%
  select(starts_with("DS"))

DSSurvey %>%
  select(contains("respond")) %>% 
  summary()

DSSurvey %>%
  slice(12)

DSSurvey %>% 
  ggplot(aes(x = visitstotal, y = clinicdistance, color =  gender_DS)) +
  geom_point() +   
  geom_jitter() +
  facet_wrap(~ income)

DSSurvey %>% 
  gather(key = sexED, value = c('gender_DS', 'DSage', 'income'))

DSSurvey %>% 
  #filter(DSage < 18) %>% 
  ggplot(aes(x = gender_DS, y = DSage, color = sexED_no)) +
  geom_point() +
  geom_jitter() 

```

#Data Play Time  
```{r}

#Sample Plot

DSSurvey %>% 
  ggplot(aes(x = visitstotal, y = clinicdistance, color =  gender_DS)) +
  geom_point() +   
  geom_jitter() +
  facet_wrap(~ income)
  
# Income vs Clinic Visits

DSSurvey %>% 
  group_by(income, DSvisit) %>% 
  summarize(n = n()) %>% 
  filter(!is.na(income)) %>% 
  ggplot(aes(x = DSvisit, y = income, color =  n)) +
  geom_point(na.rm = TRUE, size = 10) +
  ggtitle('Income vs Clinic Visits')




# income and DS education against therapies 

DSSurvey %>% 
  filter(income == "Less than $10,000"
         ) %>% 
  select(income, DSeducation, therapy_equine, DSage, ed_respond)

DSSurvey %>% 
  filter(!is.na(income)) %>%
  #melt()
  ggplot(aes(x = DSeducation, y = income, color = therapy_equine)) +
  geom_point() +   
  geom_jitter() +
  ggtitle('DS Education vs income for Equine Therapy') 

DSSurvey %>% 
  filter(!is.na(income)) %>%
  filter(!is.na(DSeducation)) %>%
  ggplot(aes(x = DSeducation, y = income, color = therapy_PT)) +
  geom_point() +   
  geom_jitter() +
  ggtitle('DS Education vs income for Physical Therapy')

DSSurvey %>% 
  filter(!is.na(income)) %>%
  filter(!is.na(DSeducation)) %>%
  ggplot(aes(x = DSeducation, y = income, color = therapy_OT)) +
  geom_point() +   
  geom_jitter() +
  ggtitle('DS Education vs income for Occupational Therapy')

DSSurvey %>% 
  filter(!is.na(income)) %>%
  filter(!is.na(DSeducation)) %>%
  ggplot(aes(x = DSeducation, y = income, color = therapy_feeding)) +
  geom_point() +   
  geom_jitter() +
  ggtitle('DS Education vs income for Feeding Therapy')

DSSurvey %>% 
  filter(!is.na(income)) %>%
  filter(!is.na(DSeducation)) %>%
  ggplot(aes(x = DSeducation, y = income, color = therapy_speech)) +
  geom_point() +   
  geom_jitter() +
  ggtitle('DS Education vs income for Speech Therapy')

DSSurvey %>% 
  filter(!is.na(income)) %>%
  filter(!is.na(DSeducation)) %>%
  ggplot(aes(x = DSeducation, y = income, color = therapy_music)) +
  geom_point() +   
  geom_jitter() +
  ggtitle('DS Education vs income for Music Therapy')


# Clinic Distance vs Frequency of Clinic Visits against income

DSSurvey %>% 
  filter(!is.na(clinicdistance)) %>%
  ggplot(aes(x = DSvisit, y = clinicdistance, color = DSage)) +
  geom_point() +   
  geom_jitter() +
  ggtitle('Distance from Clinic vs Frequency of Visits') +
  facet_wrap(~income)


# Clinic Distance vs Frequency of Clinic Visits with Curve

DSSurvey %>% 
  group_by(clinicdistance, DSvisit) %>%
  summarize(n = n()) %>%
  filter(!is.na(clinicdistance)) %>%
  ggplot(aes(x = clinicdistance, y = DSvisit, color = n)) +
  geom_point() +   
  geom_jitter() +
  geom_smooth(aes(x = as.numeric(clinicdistance), y = as.numeric(DSvisit), weight = n)) +
  ggtitle('Distance from Clinic vs Frequency of Visits') 

#DS Education vs Frequency of Clinic Visits

DSSurvey %>% 
  #filter(!is.na(DSeducation)) %>% 
  ggplot(aes(x = DSage, y = DSeducation, color =  DSvisit)) +
  geom_point(na.rm = TRUE) +
  geom_jitter() +
  ggtitle('DSeducation vs DSvisit')

# Clinic attendance vs State vs. Distance travelled

DSSurvey %>%
  filter(!is.na(clinicdistance)) %>% 
  ggplot(aes(x = clinicdistance, y = state, color = DSvisit)) +
  geom_point(na.rm = TRUE, size = 1) +
  geom_jitter() +
  ggtitle('Clinic attendance vs State vs. Distance travelled') 

DSSurvey %>% 
  select(contains('concern')) %>% 
  summary()

# Age and Gender vs Regression types
DSSurvey %>%
  filter(!is.na(regress)) %>% 
  filter(!is.na(gender_DS)) %>%
  ggplot(aes(x = gender_DS, y = DSage, color = regress)) +
  geom_point(na.rm = TRUE, size = 1) +
  geom_jitter() +
  ggtitle('gender vs age vs. did they regress') 

DSSurvey %>%
  filter(!is.na(regress_cat)) %>% 
  filter(!is.na(gender_DS)) %>%
  ggplot(aes(x = gender_DS, y = DSage, color = regress_cat)) +
  geom_point(na.rm = TRUE, size = 1) +
  geom_jitter() +
  ggtitle('gender vs age vs. did they regress (CAT)') 

DSSurvey %>%
  filter(!is.na(regress_dress)) %>% 
  filter(!is.na(gender_DS)) %>%
  ggplot(aes(x = gender_DS, y = DSage, color = regress_dress)) +
  geom_point(na.rm = TRUE, size = 1) +
  geom_jitter() +
  ggtitle('gender vs age vs. did they regress (DRESS)') 

DSSurvey %>%
  filter(!is.na(regress_attend)) %>% 
  filter(!is.na(gender_DS)) %>%
  ggplot(aes(x = gender_DS, y = DSage, color = regress_attend)) +
  geom_point(na.rm = TRUE, size = 1) +
  geom_jitter() +
  ggtitle('gender vs age vs. did they regress (ATTEND)') 

DSSurvey %>%
  filter(!is.na(regress_RW)) %>% 
  filter(!is.na(gender_DS)) %>%
  ggplot(aes(x = gender_DS, y = DSage, color = regress_RW)) +
  geom_point(na.rm = TRUE, size = 1) +
  geom_jitter() +
  ggtitle('gender vs age vs. did they regress (RW)') 

DSSurvey %>%
  filter(!is.na(regress_social)) %>% 
  filter(!is.na(gender_DS)) %>%
  ggplot(aes(x = gender_DS, y = DSage, color = regress_social)) +
  geom_point(na.rm = TRUE, size = 1) +
  geom_jitter() +
  ggtitle('gender vs age vs. did they regress (SOCIAL)') 

DSSurvey %>%
  filter(!is.na(regress_dress)) %>% 
  filter(!is.na(gender_DS)) %>%
  ggplot(aes(x = gender_DS, y = DSage, color = regress_dress)) +
  geom_point(na.rm = TRUE, size = 1) +
  geom_jitter() +
  ggtitle('gender vs age vs. did they regress (DRESS)') 

DSSurvey %>%
  filter(!is.na(regress_selfcare)) %>%
  filter(!is.na(gender_DS)) %>%
  ggplot(aes(x = gender_DS, y = DSage, color = regress_selfcare)) +
  geom_point(na.rm = TRUE, size = 1) +
  geom_jitter() +
  ggtitle('gender vs age vs. did they regress (SELFCARE)')

# Boxplot age vs did they regress

# DSSurvey %>% 
#   ggplot(x = regress, y = age) +
#   geom_boxplot()
```



```{r}

# Creating a hexbin chloropleth map based on responses per state

# libraries for the geography, cleaning, and color pallett
require(geojsonio)
require(broom)
require(rgeos)
require(viridis)

# USA hexbin map available in the geojson format here:
# https://team.carto.com/u/andrew/tables/andrew.us_states_hexgrid/public/map. 
# Download it choosing the geojson format and then:
spdf <- geojson_read("us_states_hexgrid.geojson.json",  what = "sp")
 
# Make some changes to the names (with `gsub`)
# Then use `tidy` to convert the complex S4 object (`spdf`) to 
# a data frame (`spdf_fortified`) compatible with the tidyverse
# `tidy` is a function in the `broom` package
spdf@data <- spdf@data %>% 
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
spdf_fortified <- tidy(spdf, region = "google_name")

# Calculate the centroid of each hexagon to add the label
# using package `rgeos`
centers <- 
  cbind.data.frame(data.frame(gCentroid(spdf, byid=TRUE),
                              id=spdf@data$iso3166_2))

# Calculate the number of records in 
# DSSurvey for each state
DSSurvey %>% 
  group_by(state) %>% 
  summarize(n = n()) -> state_freqs

# Add the frequencies
# to the geospatial data
spdf_fortified <- spdf_fortified %>%
  left_join(state_freqs, by=c("id"="state")) 


# plot
ggplot() +
  # plot the hexagons
  geom_polygon(data = spdf_fortified, 
               aes(fill = n,     # the frequencies
                   x = long, 
                   y = lat, 
                   group = group), 
               size=0, alpha=0.9) +
  # eliminate grid lines and axis scales to declutter
  theme_void() +
  # add this color scale, taking log of the frequencies
  # to be able to see outliers
  scale_fill_viridis(trans = "log", 
                     breaks=c(1,5,10,15,120), 
                     name="Freq of responses", 
                     guide = guide_legend( keyheight = unit(3, units = "mm"),
                                           keywidth=unit(12, units = "mm"), 
                                           label.position = "bottom", 
                                           title.position = 'top', 
                                           nrow=1) ) +
  # add the state names to the hexagons
  geom_text(data=centers, 
            aes(x=x, y=y, 
                label=id), 
            color="white", size=3, alpha=0.6) +
  # add a title at the top
  ggtitle("Response rate to Anne's survey") +
  # make the entire color scheme/locations work together
  theme(
    text = element_text(color = "#22211d"), 
    plot.background = element_rect(fill = "#f5f5f2", color = NA), 
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size= 22, 
                              hjust=0.01, 
                              color = "#4e4d47",
                              margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
    legend.position = c(0.8,1)
  ) 

  


```